### ISSUE TITLE
I found an bug

### ISSUE THREAD

**Issue by ProGamersRo** [mihayy5/mtadayz07#9]
When i use an DayZ Vehicle Spawn System and i restart the server all vehicles are gone, how i can solve this?

And i download the 0.6 r292 version and is working perfect the VSS.

**Comment by ProGamersRo** [comment]
I think i find how to fix this bug, the server with the bug i did in drive E and I remake the server in Drive C and the bug is gone, but i still test this.

**Comment by ProGamersRo** [comment]
Hmm, i think i solved that, i use your Backup System and when i restart the server i need just to /loadvehs and all vehicles are back :)), Thanks for the script: Link: https://forum.mtasa.com/topic/71924-free-mta-dayz-backup-system-v16/
But you can solve this without this script?

**Comment by mihayy5** [comment]
Well you will have to use this VSS: https://mega.nz/#!QoJSVTbJ!QfYKPD1dwoPjtedbZeS9bImlKem61z_irZPBfgk5m_s

Because the vehicles are spawned in a different way on this gamemode, also you will have to go to line 26 and change the "setElementData(veh, "dayzvehicle", 0);" to "setElementData(veh, "dayzvehicle", 1);" if you want the vehicles to be respawned after exploding.

There's no bug.

**Comment by ProGamersRo** [comment]
LOL, OK thanks and i love your work ;)
